name: ui
description: App ui package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  assets:
    path: ../assets
  l10n:
    path: ../l10n
  models:
    path: ../models
  extensions:
    path: ../extensions
  animations: ^2.0.11
  reactive_forms: ^17.0.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  very_good_analysis: ^6.0.0
