# global_options:
targets:
  $default:
    builders:
      # Json Serializable 
      json_serializable:
        options:
          explicit_to_json: true
          
      # Go router
      go_router_builder:
        generate_for:
          - lib/**_routes.dart

      # Realm
      realm:realm_generator:
        enabled: false
        # generate_for: 
        #   exclude:
        #     - packages-app//**.dart
      #     include:
      #       #- packages/**.dart
      #       - packages-app/models/**.dart
      #       - packages-app/database/**.dart

      # Riverpod
      riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/**provider.dart
            - lib/**providers.dart
            - lib/**services.dart
            - lib/**/provider/**.dart
            #
          exclude:
            - packages/**.dart
            - packages-app/**.dart

      # Freezed package
      freezed|freezed:
        enabled: true
        generate_for:
          include:
            - lib/**_provider.dart
            - lib/**_model.dart
            - lib/**_exceptions.dart
          exclude:
            - packages/**.dart
            - packages-app/**.dart
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.freezed.dart'

      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'