name: mycaselog
description: "My surgery log."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  ## Local App Packages
  models:
    path: packages-app/models
  l10n:
    path: packages-app/l10n
  database:
    path: packages-app/database
  ui:
    path: packages-app/ui
  assets:
    path: packages-app/assets
  extensions:
    path: packages-app/extensions
  annotations:
    path: packages-app/annotations
  media_manager:
    path: packages-app/media_manager
  label_ocr:
    path: packages-app/label_ocr

  ## Local Generic Packages
  utils:
    path: packages/utils
  authentication_client:
    path: packages/authentication_client/authentication_client
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  storage:
    path: packages/storage

  ## Pub dev packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.11
  async: ^2.12.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  #firebase_crashlytics: ^4.1.3
  firebase_storage: ^12.3.4
  firebase_ui_auth: ^1.16.0
  flow_builder: ^0.1.0
  flutter_adaptive_scaffold: ^0.3.1
  flutter_logger_plus: ^5.0.0
  flutter_native_splash: ^2.4.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  reactive_forms: ^17.0.1
  realm: ^20.0.0
  riverpod_annotation: ^2.6.1
  #riverpod_lint: ^3.0.0-dev.4
  shared_preferences: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_quill: ^10.8.5
  flutter_quill_to_pdf: ^2.2.5
  pdf: ^3.11.1
  printing: ^5.13.3
  image_picker: ^1.1.2
  flutter_archive: ^6.0.3
  share_plus: ^10.1.1
  file_picker: ^8.1.3
  csv: ^6.0.0
  memoized: ^2.2.6
  collection: ^1.19.0
  easy_image_viewer: ^1.5.1
  local_auth: ^2.3.0

dependency_overrides:
  #custom_lint: 0.6.10
  analyzer: 6.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.1
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  very_good_analysis: ^6.0.0
  riverpod_lint: ^2.4.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: '#dddddd'
  color_dark: '#121212'
  image: packages-app/assets/assets/logo/app_logo.png
  android_12:
    icon_background_color: '#ffffff'
    icon_background_color_dark: '#121212'
    image: packages-app/assets/assets/logo/app_logo.png
  web: false

flutter_launcher_icons:
  android: launcher_icon
  image_path: packages-app/assets/assets/logo_master/app_logo_master.png
  ios: true
  remove_alpha_ios: true

