name: models
description: App models package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_quill: ^10.8.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  realm: ^20.0.0
  recase: ^4.1.0
  ulid: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
  
  
