name: authentication_client
description: Authentication client package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  very_good_analysis: ^6.0.0
