name: media_manager
description: Media manager package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Normal packages
  path: ^1.9.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  flutter_cache_manager:  ^3.4.1
  firebase_storage: ^12.3.2
  flutter_logger_plus: ^5.0.0
  mime: ^1.0.0
  collection: ^1.19.0
  async: ^2.11.0
  annotations:
    path: ../annotations
  models:
    path: ../models
  l10n:
    path: ../l10n

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  very_good_analysis: ^6.0.0